server.port=8080
spring.application.name=hospital-management

spring.datasource.url=jdbc:h2:file:./data/hospital_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL logs in console
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Security
app.doctor.password=${APP_DOCTOR_PASSWORD:doc-pass-2026}