server.port=9000
spring.application.name=hospital-management

spring.datasource.url=jdbc:h2:mem:hospital_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Show SQL logs in console
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update